### PR TITLE
Creating UI for Submit Claim System

### PR DESCRIPTION
**Pull request by AdrianSalas1992**

### CODE REVIEW

**Review by MauricioJChavez — DISMISSED** [review]
Correct implementation of the CalimPage
As a recommendation, try not to abuse of the "&nbsp" tag, and use the classes contained in index.css (Added by Diego) to avoid including a style property when it is not needed

**Review by MauricioJChavez — DISMISSED** [review]
Quick adjustments taking into account the current dev branch

**Review by JAMendozaSa — APPROVED** [review]
Everything is ok, Approve

**Comment by DiegoE-prog** [comment]
I will close this pull request because there is another already approved that is the most recent version.

**Pull request closed without merging**
