### PR TITLE
validations

### PR DESCRIPTION
**Pull request by AdrianSalas1992**

### CODE REVIEW

**Review by JAMendozaSa — APPROVED** [review]
ok

**Review by MauricioJChavez — APPROVED** [review]
Looks good

**Comment by DiegoE-prog** [comment]
@AdrianSalas1992 Please use one branch per story, don't reuse the same branch that you use in one story in another.

**Review by MauricioJChavez — APPROVED** [review]
Approve. Just be careful using different branches for different stories

**Pull request merged**
